name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-with-values:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          port-forward: true
          values: |
            chains:
            - name: osmosis-1
              type: osmosis
              numValidators: 1
              ports:
                rest: 1313
                rpc: 26653
              resources:
                limits:
                  cpu: "0.5"
                  memory: "1G"
                requests:
                  cpu: "0.2"
                  memory: "500M"
            - name: wasmd
              type: wasmd
              numValidators: 1
              ports:
                rpc: 26659
                rest: 1319
              resources:
                limits:
                  cpu: "0.5"
                  memory: "1G"
                requests:
                  cpu: "0.2"
                  memory: "500M"
      - run: kubectl get pods
